#! /bin/sh

xcape -e "Hyper_L=Escape"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 1

echo "running bspwmrc" >> .log

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey  manage=off
bspc rule -a Zathura  state=tiled
bspc rule -a compton  manage=off

# panel
. $HOME/.config/bspwm/run_polybar.sh
